package com.object_storage_service.object_storage_service_api.mapper;

import com.object_storage_service.object_storage_service_api.domain.dto.BucketDto;
import com.object_storage_service.object_storage_service_api.domain.dto.CreateBucketRequest;
import com.object_storage_service.object_storage_service_api.domain.entity.Bucket;
import org.springframework.stereotype.Component;

@Component
public class BucketMapper {

    /**
     * Converts an API request (CreateBucketRequest) into a JPA entity (Bucket)
     * so we can save it to the database.
     *
     * Why only set 'name'?
     * - 'id' is auto-generated by @GeneratedValue(strategy = GenerationType.UUID)
     * - 'createdAt' is auto-set by @PrePersist
     * - 'objects' starts as an empty list, we don't set it here
     */
    public Bucket toEntity(CreateBucketRequest request) {
        return Bucket.builder()
                .name(request.name())   // Extract the name from the request record
                .build();               // Lombok @Builder generates this for us
    }

    /**
     * Converts a Bucket entity (from DB) into a BucketDto (for API response).
     * We also pass in objectCount separately because it's a computed value
     * (count of StorageObjects in this bucket), not stored directly on the entity.
     */
    public BucketDto toDto(Bucket bucket, long objectCount) {
        return new BucketDto(
                bucket.getId(),
                bucket.getName(),
                bucket.getCreatedAt(),
                objectCount // How many files are in this bucket
        );
    }
}
